services:
    php:
        build: ./dev/docker
        environment:
            HOST_USER_ID: ${HOST_USER_ID}
            HOST_GROUP_ID: ${HOST_GROUP_ID}
            HOST_IP: ${HOST_IP:-}
        image: petersons/d2l-client
        volumes:
            - .:/app/src
